### ISSUE TITLE
New operative to launchcontainers

### ISSUE THREAD

**Issue by leandrolecca** [garikoitz/launchcontainers#26]
1. Create a project folder
2. Convert your dicoms with heudiconv
3. Copy an example_config.yaml to nifti folder
4. Edit example_config.yaml
5. Create the symlinks by running 'python launchcontainers.py -lcc .... -cc .... -ssl ....' (always without --run_lc)
6. Check that all the symlinks are successfully created and that the configs are copied (use 'tree' command with color coding to check that there are not broken links)
7. 'cd' to nifti/derivatives/container_version/analysis-x/
8. Edit config.json (tractparams.csv for the case of rtp-pipeline, etc..)
9. Run the container by running 'python launchcontainers.py -lcc ./config_lc.yaml --run_lc'

**Comment by garikoitz** [comment]
NOTE that the config_lc.yaml file will be a live file that we will be editing every time that we launch a new analysis, and that the good ones will be copies to both the derivatives/container/analysis and to the output folder of the each subject, so that we know what we used every time

**Comment by yongninglei** [comment]
I would like to propose this work flow for the launchcontainer

0. git clone garikoitz/launchcontainer master branch
1. Create a project folder (remain the same)
2. Convert your dicoms with heudiconv (remain the same)
3. Copy an example_config.yaml, subSesList.txt, and container specific config .json to nifti folder, make their name specific to your study
4. Edit all three files to fit your study and analysis
5. Create the symlinks by running '$python launchcontainers.py -lcc .... -cc .... -ssl ....' (always without --run_lc)
6. Check that all the symlinks are successfully created and that the configs are copied and fits your analysis requirements (use 'tree' command with color coding to check that there are no broken links) (I will edit the copy so that the files are copied with certain name and we will know if the copy are success from the file name)

7 Run the container by running using up arrow and only add --run_lc flag

**Comment by garikoitz** [comment]
Tiger sis this as part of issue#23 and it will be checked in PR Issue/23
